<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\SmartMeterStudio.Core\SmartMeterStudio.Core.csproj" />
    <ProjectReference Include="..\..\src\SmartMeterStudio.Protocol\SmartMeterStudio.Protocol.csproj" />
    <ProjectReference Include="..\..\src\SmartMeterStudio.Protocol.Transport\SmartMeterStudio.Protocol.Transport.csproj" />
  </ItemGroup>
</Project>
